// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqyQYnYUkqK_7b_MUA_2HdWSV2xhdp60',
    appId: '1:345955646134:web:b9cfa5f0f101afb60e4417',
    messagingSenderId: '345955646134',
    projectId: 'ai-resume-analyzer-f2baa',
    authDomain: 'ai-resume-analyzer-f2baa.firebaseapp.com',
    storageBucket: 'ai-resume-analyzer-f2baa.firebasestorage.app',
    measurementId: 'G-9TS63MC8RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMmg1qvK-HFllxV5cbMABsyEN_UmiVfI',
    appId: '1:345955646134:android:70303a7615ef861d0e4417',
    messagingSenderId: '345955646134',
    projectId: 'ai-resume-analyzer-f2baa',
    storageBucket: 'ai-resume-analyzer-f2baa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9ddeJP0M0XsY4A2y14XgFA7m169Umkg',
    appId: '1:345955646134:ios:826880a55a7a71590e4417',
    messagingSenderId: '345955646134',
    projectId: 'ai-resume-analyzer-f2baa',
    storageBucket: 'ai-resume-analyzer-f2baa.firebasestorage.app',
    iosBundleId: 'com.example.aiResumeAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt9ddeJP0M0XsY4A2y14XgFA7m169Umkg',
    appId: '1:345955646134:ios:826880a55a7a71590e4417',
    messagingSenderId: '345955646134',
    projectId: 'ai-resume-analyzer-f2baa',
    storageBucket: 'ai-resume-analyzer-f2baa.firebasestorage.app',
    iosBundleId: 'com.example.aiResumeAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCqyQYnYUkqK_7b_MUA_2HdWSV2xhdp60',
    appId: '1:345955646134:web:516d2d1c44a3f0940e4417',
    messagingSenderId: '345955646134',
    projectId: 'ai-resume-analyzer-f2baa',
    authDomain: 'ai-resume-analyzer-f2baa.firebaseapp.com',
    storageBucket: 'ai-resume-analyzer-f2baa.firebasestorage.app',
    measurementId: 'G-YE09H4B00Y',
  );
}
